// All 49 NREMT paramedic drug entries from the PDF
const DRUGS = [
  {
    id: 'fentanyl-rsi',
    generic: 'Fentanyl',
    trade: 'Sublimaze',
    category: 'RSI',
    class: 'CNS depressant',
    action: 'Depresses the CNS by inhibiting the release of neurotransmitters reducing neuronal excitability',
    indications: 'Sedation prior to RSI',
    contraindications: 'Head injury, myasthenia gravis',
    sideEffects: 'Respiratory depression, hypotension, ALOC',
    adultDose: '25–100 mcg SIVP/IM',
    pediatricDose: '2 mcg/kg SIVP/IM'
  },
  {
    id: 'fentanyl-pain',
    generic: 'Fentanyl',
    trade: 'Sublimaze',
    category: 'Pain',
    class: 'CNS depressant, narcotic analgesic',
    action: 'Alters pain perception by binding to opiate receptors increasing pain threshold',
    indications: 'Pain',
    contraindications: 'Head injury (increases ICP), myasthenia gravis',
    sideEffects: 'Bradycardia, hypotension, respiratory depression, laryngospasms',
    adultDose: 'SIVP/IO/IM: 25–100 mcg',
    pediatricDose: 'SIVP/IO/IM: 2 mcg/kg'
  },
  {
    id: 'diazepam-seizures',
    generic: 'Diazepam',
    trade: 'Valium',
    category: 'Seizures',
    class: 'CNS depressant, anticonvulsant',
    action: 'Suppresses seizure activity, relaxes skeletal muscles',
    indications: 'Seizures',
    contraindications: 'Hypotension, head injury, patients taking sedatives or intoxicated',
    sideEffects: 'Respiratory depression, hypotension, ALOC, tachycardia',
    adultDose: '5–10 mg IV/IM',
    pediatricDose: 'IV: 0.2–0.5 mg/kg (5–15 mg max); PR: 0.5 mg/kg, repeat every 10–15 min PRN (3 doses max)'
  },
  {
    id: 'diazepam-cardiac',
    generic: 'Diazepam',
    trade: 'Valium',
    category: 'Cardiac',
    class: 'CNS depressant, anxiolytic',
    action: 'Relaxes skeletal muscles, depressing the CNS inducing amnesia',
    indications: 'Premedication for synchronized cardioversion and pacing',
    contraindications: 'Hypotension, head injury, patients on sedatives or intoxicated',
    sideEffects: 'Orthostatic hypotension, respiratory depression, tachycardia, ALOC',
    adultDose: '5–15 mg IV',
    pediatricDose: '0.2–0.5 mg/kg IV (5–16 mg max)'
  },
  {
    id: 'procainamide',
    generic: 'Procainamide',
    trade: 'Pronestyl, Procan',
    category: 'Cardiac',
    class: 'Antidysrhythmic: Sodium Channel Blocker',
    action: 'Decreases dromotropy, automaticity, and myocardial excitability',
    indications: 'All tachydysrhythmias',
    contraindications: '2nd and 3rd degree heart blocks, Torsades de Pointes, digitalis toxicity',
    sideEffects: 'Hypotension, dizziness, headache',
    adultDose: '100 mg IV over 5 min',
    pediatricDose: '15 mg/kg IV over 30–60 min'
  },
  {
    id: 'amyl-nitrate-cardiac',
    generic: 'Amyl Nitrate',
    trade: 'Vaporole',
    category: 'Cardiac',
    class: 'Nitrate, vasodilator, anti-anginal',
    action: 'Relaxes vascular smooth muscle decreasing MvO₂ and PVR',
    indications: 'Hypertension, angina',
    contraindications: 'Hypotension, recent erectile dysfunction drug use',
    sideEffects: 'Headache, dizziness, facial flushing',
    adultDose: '1–2; 0.3 mL ampules inhaled over 30 sec, repeat every 1–2 min PRN',
    pediatricDose: '1; 0.3 mL ampule inhaled over 30 sec, repeat every 1–2 min PRN'
  },
  {
    id: 'amyl-nitrate-od',
    generic: 'Amyl Nitrate',
    trade: 'Vaporole',
    category: 'Overdose/Poisoning',
    class: 'Antidote',
    action: 'Decreases cyanide toxicity by turning hemoglobin into methemoglobin which forms a complex with cyanide ions to create cyanomethemoglobin which is then excreted in the liver',
    indications: 'Cyanide poisoning',
    contraindications: 'None when treating cyanide poisoning',
    sideEffects: 'Headache, dizziness, facial flushing, tachycardia, hypotension',
    adultDose: '1–2; 0.3 mL ampules inhaled over 30 sec, repeat every 1–2 min PRN',
    pediatricDose: '1; 0.3 mL ampule inhaled over 30 sec, repeat every 1–2 min PRN'
  },
  {
    id: 'etomidate',
    generic: 'Etomidate',
    trade: 'Amidate',
    category: 'RSI',
    class: 'CNS depressant, anesthetic',
    action: 'Produces anesthesia and amnesia',
    indications: 'Sedation prior to RSI',
    contraindications: 'Status asthmaticus, immunosuppressed patients',
    sideEffects: 'Respiratory depression, hypotension, dysrhythmias',
    adultDose: '0.2–0.6 mg/kg IV over 1 min; common RSI dose is 20 mg',
    pediatricDose: '0.2–0.6 mg/kg IV over 1 min; only use in children 10+ y.o.'
  },
  {
    id: 'droperidol',
    generic: 'Droperidol',
    trade: 'Inapsine',
    category: 'RSI',
    class: 'CNS depressant',
    action: 'Antagonizes and blocks dopamine receptors causing CNS depression',
    indications: 'Sedation prior to RSI',
    contraindications: 'Children < 2 y.o., hypotensive, hepatic/renal disease',
    sideEffects: 'Hypotension, respiratory depression, dystonic reactions',
    adultDose: '2.5–10 mg IV/IM, repeat one time in 10 min PRN',
    pediatricDose: '0.05–0.1 mg/kg IV/IM'
  },
  {
    id: 'vasopressin',
    generic: 'Vasopressin',
    trade: 'Pitressin',
    category: 'Cardiac',
    class: 'Vasopressor',
    action: 'Stimulates smooth muscle receptors to cause vasoconstriction',
    indications: 'Cardiac arrest to increase PVR with CPR',
    contraindications: 'Ischemic heart disease',
    sideEffects: 'Bradycardia, arrhythmias, PACs, heart blocks',
    adultDose: 'Arrest: 40 units IV (one-time dose to replace 1st or 2nd dose of epinephrine)',
    pediatricDose: 'Not recommended'
  },
  {
    id: 'rocuronium',
    generic: 'Rocuronium',
    trade: 'Zemuron',
    category: 'RSI',
    class: 'Non-depolarizing paralytic',
    action: 'Binds with cholinergic receptors; inhibits neuromuscular transmission',
    indications: 'RSI, skeletal muscle relaxation',
    contraindications: 'Hypersensitivity',
    sideEffects: 'Respiratory depression, tachycardia, apnea',
    adultDose: '0.6 mg/kg IV; 0.1–0.2 mg/kg/min IVPB',
    pediatricDose: '0.6 mg/kg IV'
  },
  {
    id: 'racemic-epi',
    generic: 'Racemic Epinephrine',
    trade: 'Vaponefrin, Micronefrin',
    category: 'Respiratory',
    class: 'Sympathomimetic bronchodilator',
    action: 'Stimulates bronchial smooth muscle dilation',
    indications: 'Croup (laryngotracheobronchitis), bronchospasm',
    contraindications: 'Epiglottitis',
    sideEffects: 'Tremors, tachycardia, anxiety, hypertension',
    adultDose: '0.25–0.75 mL of 2.25% solution diluted in 2 mL NS nebulized',
    pediatricDose: '0.25–0.75 mL of 2.25% solution diluted in 2 mL NS nebulized'
  },
  {
    id: 'atropine-od',
    generic: 'Atropine Sulfate',
    trade: '—',
    category: 'Overdose/Poisoning',
    class: 'Antidysrhythmic, parasympatholytic, antidote',
    action: 'Blocks cholinergic receptors increasing chronotropy and dromotropy',
    indications: 'Organophosphate or nerve agent poisoning',
    contraindications: 'None in emergency settings',
    sideEffects: 'Tachycardia, HTN, palpitations, increased MvO₂',
    adultDose: '2 mg IM repeat PRN every 3–5 min',
    pediatricDose: '0.05 mg/kg IM with a single dose range of 0.1 mg (min) to 2 mg (max), repeat PRN every 3–5 min'
  },
  {
    id: 'atropine-cardiac',
    generic: 'Atropine Sulfate',
    trade: '—',
    category: 'Cardiac',
    class: 'Antidysrhythmic; parasympatholytic',
    action: 'Blocks cholinergic receptors increasing chronotropy and dromotropy',
    indications: 'Symptomatic bradycardia',
    contraindications: '2nd and 3rd degree heart blocks, suspected AMI',
    sideEffects: 'Tachycardia, HTN, palpitations, increased MvO₂',
    adultDose: 'IV/IO: 0.5 mg, repeat PRN every 3–5 min, 3 mg total max',
    pediatricDose: 'IV/IO: 0.02 mg/kg (min 0.1 mg, max 0.5 mg), 3 mg total max'
  },
  {
    id: 'pralidoxime',
    generic: 'Pralidoxime Chloride',
    trade: '2-PAM Chloride, Protopam',
    category: 'Overdose/Poisoning',
    class: 'Cholinesterase reactivator, antidote',
    action: 'Decreases acetylcholine and its parasympathetic effects, deactivates certain chemical organophosphates/nerve agents through a direct chemical reaction',
    indications: 'Organophosphate and nerve agent poisoning',
    contraindications: 'Inorganic phosphate poisoning',
    sideEffects: 'Tachycardia, hypertension, blurred vision',
    adultDose: 'IM/SQ: 1–2 g (administer after atropine)',
    pediatricDose: 'IM/SQ: 1–2 mg/kg (administer after atropine)'
  },
  {
    id: 'furosemide',
    generic: 'Furosemide',
    trade: 'Lasix',
    category: 'Cardiac',
    class: 'Loop diuretic',
    action: 'Increases urinary output, decreasing PVR and workload on the heart',
    indications: 'CHF, cardiogenic pulmonary edema',
    contraindications: 'Dehydration, hypotension, hypovolemia',
    sideEffects: 'Hearing loss, tinnitus, hyperglycemia (rales/fluid shift = ↑ urinary output)',
    adultDose: '0.5–1 mg/kg or 40–80 mg SIVP; if no response then 2 mg/kg',
    pediatricDose: '1 mg/kg SIVP'
  },
  {
    id: 'terbutaline',
    generic: 'Terbutaline',
    trade: 'Brethair, Brethine',
    category: 'OB/GYN',
    class: 'Tocolytic',
    action: 'Relaxes uterine smooth muscle to inhibit contractions',
    indications: 'Preterm labor to stop uterine contractions (secondary to mag sulfate)',
    contraindications: 'Uncontrolled tachydysrhythmias, hypertension, DM',
    sideEffects: 'Tachycardia, hypertension, PVCs, headache',
    adultDose: '10 mcg/min IVPB titrate to effect (80 mcg/min max)',
    pediatricDose: 'N/A'
  },
  {
    id: 'amiodarone',
    generic: 'Amiodarone',
    trade: 'Cordarone',
    category: 'Cardiac',
    class: 'Antidysrhythmic',
    action: 'Prolongs the duration of the action potential and refractory periods',
    indications: 'All tachydysrhythmias',
    contraindications: '2nd and 3rd degree heart blocks, cardiogenic shock',
    sideEffects: 'Headache, dizziness, hypotension',
    adultDose: 'Arrest: 300 mg, then 150 mg; Tachy + Pulse: 150 mg over 10 min',
    pediatricDose: 'Arrest: 5 mg/kg IV/IO, repeat PRN (15 mg/kg total max); Tachy + Pulse: 5 mg/kg IV/IO over 20–60 min'
  },
  {
    id: 'lidocaine',
    generic: 'Lidocaine',
    trade: 'Xylocaine',
    category: 'Cardiac',
    class: 'Antidysrhythmic: Sodium Channel Blocker',
    action: 'Decreases automaticity and dromotropy, suppressing ventricular ectopy and dysrhythmias',
    indications: 'Ventricular dysrhythmias including VF/VT with or without pulse',
    contraindications: '2nd and 3rd degree heart blocks, bradycardic, junctional, and idioventricular rhythms',
    sideEffects: 'Bradycardia, hypotension, headache',
    adultDose: 'Arrest/Malignant PVCs: 1–1.5 mg/kg IV/IO, repeat 0.5–0.75 every 3–5 min (3 mg/kg total max)',
    pediatricDose: 'Arrest/Malignant PVCs: 1 mg/kg IV/IO, repeat 0.5–0.75 every 3–5 min (100 mg total max)'
  },
  {
    id: 'dopamine',
    generic: 'Dopamine',
    trade: 'Intropin',
    category: 'Cardiac',
    class: 'Sympathomimetic, antidysrhythmic, vasopressor',
    action: 'Increases inotropy, chronotropy, dromotropy, automaticity, and systemic vascular resistance',
    indications: 'Hypotension, cardiogenic shock or CHF',
    contraindications: 'Hypovolemia without prior fluid resuscitation',
    sideEffects: 'Headache, palpitations, angina, HTN, tachycardia',
    adultDose: 'Inotropic effects: 2–10 mcg/kg/min IVPB; Vasopressor effects: 10–20 mcg/kg/min IVPB',
    pediatricDose: 'Inotropic effects: 2–10 mcg/kg/min IVPB; Vasopressor effects: 10–20 mcg/kg/min IVPB'
  },
  {
    id: 'diphenhydramine-od',
    generic: 'Diphenhydramine',
    trade: 'Benadryl',
    category: 'Overdose/Poisoning',
    class: 'Antihistamine, anticholinergic',
    action: "Relieves muscle contractions and restores the excitatory–inhibitory balance in the brain's extrapyramidal motor system",
    indications: 'Dystonic reactions and extrapyramidal symptoms',
    contraindications: 'Late stage pregnancy or lactation, elderly patients with heart disease',
    sideEffects: 'Dizziness, drowsiness, hypotension, tachycardia',
    adultDose: '25–50 mg IV at 25 mg/min, repeat PRN',
    pediatricDose: '1–2 mg/kg IV (IM not recommended)'
  },
  {
    id: 'diphenhydramine-allergies',
    generic: 'Diphenhydramine',
    trade: 'Benadryl',
    category: 'Allergies',
    class: 'Antihistamine',
    action: 'Blocks histamines at receptor sites',
    indications: 'Mild to moderate allergic reactions, anaphylaxis following the administration of epinephrine',
    contraindications: 'Neonates, late stage pregnancy, elderly patients with heart disease',
    sideEffects: 'Hypotension, tachycardia, dry mouth, seizures, dilated pupils',
    adultDose: '25–50 mg IV at 25 mg/min, repeat PRN',
    pediatricDose: '1–2 mg/kg IV (IM not recommended)'
  },
  {
    id: 'midazolam-cardiac',
    generic: 'Midazolam',
    trade: 'Versed',
    category: 'Cardiac',
    class: 'CNS depressant, anxiolytic',
    action: 'Relaxes skeletal muscles, depressing the CNS inducing amnesia',
    indications: 'Premedication for synchronized cardioversion and pacing',
    contraindications: 'Hypotension, head injury, drug or alcohol intoxication',
    sideEffects: 'Respiratory depression, apnea, bradycardia, hypotension',
    adultDose: 'IV: 1–2.5 mg or IM/IN: 5 mg; repeat in 5 min PRN; 10 mg total max; titrate to sedation',
    pediatricDose: 'IV: 0.1–0.15 mg/kg or IN: 0.2–0.3 mg/kg'
  },
  {
    id: 'midazolam-seizures',
    generic: 'Midazolam',
    trade: 'Versed',
    category: 'Seizures',
    class: 'CNS depressant, anticonvulsant',
    action: 'Relaxes skeletal muscles and suppresses seizure activity',
    indications: 'Seizures',
    contraindications: 'Hypotension, head injury, drug or alcohol intoxication',
    sideEffects: 'Respiratory depression, bradycardia, hypotension, ALOC',
    adultDose: '1–2.5 mg IV or 5 mg IM/IN',
    pediatricDose: '0.1–0.15 mg/kg IV/IM or 0.2–0.3 mg/kg IN'
  },
  {
    id: 'midazolam-rsi',
    generic: 'Midazolam',
    trade: 'Versed',
    category: 'RSI',
    class: 'CNS depressant, benzodiazepine',
    action: 'Produces amnesia and relaxes skeletal muscles through short-term CNS depression',
    indications: 'Sedation prior to RSI',
    contraindications: 'Hypotension, head injury, drug or alcohol intoxication',
    sideEffects: 'Respiratory depression, bradycardia, hypotension, phlebitis',
    adultDose: '1–2.5 mg IV or 5 mg IM/IN',
    pediatricDose: '0.1–0.15 mg/kg IV/IM or 0.2–0.3 mg/kg IN'
  },
  {
    id: 'ipratropium',
    generic: 'Ipratropium',
    trade: 'Atrovent',
    category: 'Respiratory',
    class: 'Parasympatholytic/anticholinergic bronchodilator',
    action: 'Blocks ACh at bronchial smooth muscle receptors causing bronchodilation and reducing respiratory secretions',
    indications: 'Bronchospasms associated with asthma and COPD',
    contraindications: 'Patients that have already received atropine',
    sideEffects: 'Anxiety, tachycardia, hypertension, airway dryness',
    adultDose: '0.5 mg nebulized',
    pediatricDose: '0.25 mg nebulized'
  },
  {
    id: 'nitroglycerine',
    generic: 'Nitroglycerine',
    trade: 'Nitrolingual, Nitrostat, Nitrobid',
    category: 'Cardiac',
    class: 'Nitrate, vasodilator, anti-anginal',
    action: 'Relaxes vascular smooth muscle increasing coronary artery perfusion, decreasing preload, afterload, and MvO₂ demand',
    indications: 'Cardiac chest pain (angina or suspected AMI)',
    contraindications: 'Hypotension (SBP <90 mmHg), recent erectile dysfunction drug use',
    sideEffects: 'Orthostatic hypotension, headache, flushing, rebound hypertension',
    adultDose: 'SL: 0.3–0.4 mg, repeat in 5 min PRN, 3 doses max; TD: 0.5–2 inches paste',
    pediatricDose: 'Not recommended'
  },
  {
    id: 'adenosine',
    generic: 'Adenosine',
    trade: 'Adenocard',
    category: 'Cardiac',
    class: 'Miscellaneous antidysrhythmic',
    action: 'Slows down conduction of SA/AV nodes',
    indications: 'SVT/PSVT',
    contraindications: '2nd and 3rd degree heart blocks, sick sinus syndrome',
    sideEffects: 'Asystole, bradycardia, chest pain/pressure',
    adultDose: '6 mg, 12 mg, 12 mg RIVP, followed by a 10–20 mL NS flush',
    pediatricDose: '0.1 mg/kg, then 0.2 mg/kg RIVP, followed by 10 mL NS flush (12 mg single dose max)'
  },
  {
    id: 'ondansetron',
    generic: 'Ondansetron',
    trade: 'Zofran',
    category: 'Nausea/Vomiting',
    class: 'Anti-emetic, anti-vertigo',
    action: 'Blocks serotonin in CTZ in the CNS and vagal nerve terminals to reduce nausea',
    indications: 'Prevention of nausea and vomiting',
    contraindications: 'Hypersensitivity, may prolong QT interval',
    sideEffects: 'Headache, abdominal pain, constipation, hypoxia',
    adultDose: '4 mg IV/IM/PO',
    pediatricDose: '0.1 mg/kg'
  },
  {
    id: 'epi-allergies',
    generic: 'Epinephrine',
    trade: 'Adrenaline',
    category: 'Allergies',
    class: 'Sympathomimetic, catecholamine',
    action: 'Acts directly on alpha and beta receptors of the sympathetic NS',
    indications: 'Anaphylaxis or severe allergic reaction',
    contraindications: 'Hypertension, tachydysrhythmias, hypovolemia',
    sideEffects: 'Anxiety, tremors, dysrhythmias, seizures, HTN',
    adultDose: 'SIVP: 0.1–0.5 mg 1:10,000; IM: 0.3–0.5 mg 1:1,000',
    pediatricDose: 'SIVP: 0.01 mg/kg 1:10,000; IM: 0.01 mg/kg 1:1,000 (0.3 mg max single dose)'
  },
  {
    id: 'epi-cardiac',
    generic: 'Epinephrine',
    trade: 'Adrenaline',
    category: 'Cardiac',
    class: 'Sympathomimetic, antidysrhythmic, vasopressor',
    action: 'Increases inotropy, chronotropy, dromotropy, & automaticity',
    indications: 'Cardiac arrest (asystole, PEA, VF, pulseless VT)',
    contraindications: 'None in cardiac arrest',
    sideEffects: 'Tachycardia, hypertension, palpitations, chest pain',
    adultDose: 'Arrest: 1 mg 1:10,000 IV/IO repeat every 3–5 min PRN',
    pediatricDose: 'Arrest & Symptomatic Bradycardia: 0.01 mg/kg 1:10,000 IV/IO, repeat every 3–5 min PRN'
  },
  {
    id: 'epi-respiratory',
    generic: 'Epinephrine',
    trade: 'Adrenaline',
    category: 'Respiratory',
    class: 'Sympathomimetic, bronchodilator',
    action: 'Dilates bronchial smooth muscle',
    indications: 'Severe reactive airway disease (asthma, COPD)',
    contraindications: 'Hypertension, tachydysrhythmias, hypovolemia',
    sideEffects: 'Tachycardia, hypertension, dysrhythmias, chest pain, seizures',
    adultDose: '0.3–0.5 mg 1:1,000 IM',
    pediatricDose: '0.01 mg/kg 1:1,000 IM (0.3 mg max single dose)'
  },
  {
    id: 'morphine',
    generic: 'Morphine Sulfate',
    trade: 'Duramorph, Astramorph',
    category: 'Pain',
    class: 'CNS depressant, narcotic analgesic',
    action: 'Binds to opioid receptors to produce analgesia and sedation; causes vasodilation decreasing PVR reducing preload, afterload, and MvO₂',
    indications: 'Pain, including CP resulting from suspected AMI or acute pulmonary edema',
    contraindications: 'Head injury, ALOC, hypovolemia',
    sideEffects: 'Severe hypotension, respiratory depression/arrest',
    adultDose: 'SIVP: 2–10 mg (rate: 1–2 mg/min), repeat in 5 min PRN; IM: 5–20 mg',
    pediatricDose: '0.1–0.2 mg/kg IV/IM, repeat in 5 min PRN (15 mg max dose)'
  },
  {
    id: 'vecuronium',
    generic: 'Vecuronium',
    trade: 'Norcuron',
    category: 'RSI',
    class: 'Non-depolarizing paralytic',
    action: 'Binds with cholinergic receptors; inhibits neuromuscular transmission',
    indications: 'RSI',
    contraindications: 'Myasthenia Gravis',
    sideEffects: 'Respiratory depression, apnea, prolonged paralysis',
    adultDose: '0.1 mg/kg IV',
    pediatricDose: '0.1 mg/kg IV'
  },
  {
    id: 'haloperidol',
    generic: 'Haloperidol',
    trade: 'Haldol',
    category: 'Chemical Restraint',
    class: 'CNS depressant, butyrophenone, antipsychotic',
    action: 'Antagonizes and blocks dopamine receptors',
    indications: 'Chemical restraint for acute psychotic episodes',
    contraindications: 'Comatose patients; patients with Parkinson\'s',
    sideEffects: 'Sedation, dystonic reactions, respiratory depression',
    adultDose: 'IM: 2–5 mg',
    pediatricDose: 'Not recommended'
  },
  {
    id: 'diltiazem',
    generic: 'Diltiazem Hydrochloride',
    trade: 'Cardizem',
    category: 'Cardiac',
    class: 'Antidysrhythmic: Calcium Channel Blocker',
    action: 'Inhibits calcium influx across cell membranes causing coronary vasodilation and smooth muscle relaxation, slows SA/AV node conduction',
    indications: 'Symptomatic A-Fib, A-Flutter, SVT, PSVT',
    contraindications: 'Hypotension, 2nd and 3rd degree heart blocks',
    sideEffects: 'Headache, edema, bradycardia',
    adultDose: 'IV: 15–20 mg or 0.25 mg/kg repeat in 15 min at 20–25 mg; IVP: 5–15 mg/hr',
    pediatricDose: 'Not recommended'
  },
  {
    id: 'thiamine',
    generic: 'Thiamine',
    trade: 'Vitamin B1',
    category: 'Diabetes',
    class: 'Vitamin',
    action: 'Coenzyme necessary for metabolism of glucose',
    indications: 'Coma associated with DT prior to administration of D50W',
    contraindications: 'None',
    sideEffects: 'Mild hypotension, weakness, sweating',
    adultDose: '50–100 mg IV/IM',
    pediatricDose: '10–25 mg IV/IM'
  },
  {
    id: 'albuterol',
    generic: 'Albuterol',
    trade: 'Proventil, Ventolin, Alupent',
    category: 'Respiratory',
    class: 'Sympathomimetic bronchodilator',
    action: 'Relaxes bronchial smooth muscle causing bronchodilation and decreased airway resistance',
    indications: 'Bronchospasms',
    contraindications: 'Symptomatic tachydysrhythmias, severe hypertension',
    sideEffects: 'Tachycardia, wheezing, hypertension, anxiety, arrhythmias, chest pain',
    adultDose: '2.5–5 mg over 5–15 min nebulized at 6–8 LPM of oxygen',
    pediatricDose: '0.05–0.15 mg/kg over 5–15 min nebulized at 6–8 LPM of oxygen, PRN'
  },
  {
    id: 'aspirin',
    generic: 'Aspirin',
    trade: 'Acetylsalicylic acid, Bayer',
    category: 'Cardiac',
    class: 'Antiplatelet aggregate',
    action: 'Blocks platelet aggregation by slowing down prostaglandin synthesis',
    indications: 'Chest pain with suspected AMI',
    contraindications: 'Active GI bleeding or ulcers, patients with known bleeding disorders',
    sideEffects: 'GI bleeding, epigastric pain, wheezing',
    adultDose: '162–325 mg PO',
    pediatricDose: 'Not recommended'
  },
  {
    id: 'dextrose',
    generic: 'Dextrose',
    trade: '—',
    category: 'Diabetes',
    class: 'Hyperglycemic agent',
    action: 'Increase blood glucose levels',
    indications: 'Hypoglycemia',
    contraindications: 'None',
    sideEffects: 'Venous irritation',
    adultDose: '25 g (50 mL) D50W SIVP',
    pediatricDose: '0.5–1 g/kg D25W SIVP (note: use D10W for neonates)'
  },
  {
    id: 'naloxone',
    generic: 'Naloxone',
    trade: 'Narcan',
    category: 'Overdose/Poisoning',
    class: 'Competitive narcotic antagonist, antidote',
    action: 'Competes with narcotics at the opiate receptor sites in the CNS',
    indications: 'Known or suspected narcotic OD with RR < 8, decreased TV/MV',
    contraindications: 'Hypersensitivity',
    sideEffects: 'Tachycardia, hypertension, withdrawal, tremors, seizures',
    adultDose: 'IV/IM/IN: 0.4–2 mg, repeat in 5 min PRN; 10 mg total max',
    pediatricDose: 'IV/IM/IN: 0.1 mg/kg, repeat in 5 min PRN; 10 mg total max'
  },
  {
    id: 'mag-cardiac',
    generic: 'Magnesium Sulfate',
    trade: '—',
    category: 'Cardiac',
    class: 'Antidysrhythmic',
    action: 'Physiological calcium channel blocker',
    indications: 'Torsades de Pointes',
    contraindications: 'Shock, heart blocks, hypermagnesemia',
    sideEffects: 'Cramps, flushing, sweating, bradycardia',
    adultDose: 'Arrest due to Torsades/Hypomagnesemia: 1–2 g IV diluted in 10 mL D5W over 5 min; Torsades + Pulse or AMI + Hypomagnesemia: 1–2 g IV diluted in 50 mL D5W',
    pediatricDose: '25–50 mg/kg SIVP over 10–20 min (2 g max dose)'
  },
  {
    id: 'mag-ob',
    generic: 'Magnesium Sulfate',
    trade: 'OB use',
    category: 'Seizures',
    class: 'CNS depressant, anticonvulsant',
    action: 'Produces neuromuscular blockade in CNS to suppress seizure activity',
    indications: 'Seizures associated with eclampsia and alcohol withdrawal',
    contraindications: 'Shock, heart blocks, hypermagnesemia',
    sideEffects: 'Respiratory depression, hypotension, decreased tendon reflexes',
    adultDose: '1–4 g IV',
    pediatricDose: '25–50 mg/kg SIVP over 10–20 min (2 g max dose)'
  },
  {
    id: 'sodium-bicarb',
    generic: 'Sodium Bicarbonate',
    trade: '—',
    category: 'Overdose/Poisoning',
    class: 'Antidote, alkalizing agent',
    action: 'Decreases precipitation of myoglobin in renal tubules; binds with hydrogen ions and neutralizes excess acid buildup',
    indications: 'Tricyclic antidepressant overdose, suspected hyperkalemia/metabolic acidosis',
    contraindications: 'None in the emergency setting, use caution with CHF patients',
    sideEffects: 'Alkalosis, hyperreflexia, twitching, pulmonary edema',
    adultDose: '1 mEq/kg IV/IO',
    pediatricDose: '1 mEq/kg IV/IO'
  },
  {
    id: 'succinylcholine',
    generic: 'Succinylcholine',
    trade: 'Anectine',
    category: 'RSI',
    class: 'Depolarizing neuromuscular blocker, paralytic',
    action: 'Causes depolarization of skeletal muscle cells followed by paralysis due to continued binding with cholinergic receptors',
    indications: 'RSI',
    contraindications: 'Malignant hyperthermia, myasthenia gravis',
    sideEffects: 'Muscle stiffness or pain, prolonged respiratory depression, hypotension',
    adultDose: '1–1.5 mg/kg IV or 3–4 mg/kg IM (max 150 mg)',
    pediatricDose: '1–1.5 mg/kg IV'
  },
  {
    id: 'calcium-chloride',
    generic: 'Calcium Chloride',
    trade: '—',
    category: 'Overdose/Poisoning',
    class: 'Antidote',
    action: 'Increases inotropy, ventricular automaticity, and restores myocardial conduction',
    indications: 'Calcium channel blocker OD, magnesium OD/hypermagnesemia, hyperkalemia',
    contraindications: 'Hypercalcemia, digitalis toxicity, VF',
    sideEffects: 'Bradycardia, hypotension, syncope, acidosis',
    adultDose: '500–1000 mg SIVP, repeat in 10 min PRN',
    pediatricDose: '20 mg/kg SIVP, repeat in 10 min PRN, 1 g single dose max'
  },
  {
    id: 'glucagon-diabetes',
    generic: 'Glucagon',
    trade: 'GlucaGen',
    category: 'Diabetes',
    class: 'Anti-hypoglycemic agent',
    action: 'Breaks down glycogen into glucose',
    indications: 'Hypoglycemia with no IV access established',
    contraindications: 'None',
    sideEffects: 'Tachycardia, dizziness, hyper/hypo-tension',
    adultDose: '0.5–1 mg IM; repeat in 10 min PRN',
    pediatricDose: '0.5–1 mg IM'
  },
  {
    id: 'glucagon-od',
    generic: 'Glucagon',
    trade: 'GlucaGen',
    category: 'Overdose/Poisoning',
    class: 'Antidote',
    action: 'Positive inotropic and chronotropic properties',
    indications: 'Beta blocker overdose, calcium channel blocker overdose',
    contraindications: 'Pheochromocytoma, adrenal insufficiency, insulinoma',
    sideEffects: 'Tachycardia, hypertension, hypotension, dizziness',
    adultDose: 'Overdose: 3 mg IV initial dose, followed by infusion at 3 mg/hr PRN',
    pediatricDose: 'Not recommended'
  },
  {
    id: 'oxytocin',
    generic: 'Oxytocin',
    trade: 'Pitocin',
    category: 'OB/GYN',
    class: 'Hormone, oxytocic agent',
    action: 'Causes uterine smooth muscle contraction (promotes uterine contraction to stop hemorrhage)',
    indications: 'Post-partum hemorrhage (> 500 mL)',
    contraindications: 'Do not use prior to delivery of placenta or prior to delivery of all babies in multiple-birth pregnancies',
    sideEffects: 'Hypotension, dysrhythmias, anaphylaxis',
    adultDose: 'IVPB: 10–20 units in 1 L NS or D5W titrate to effect; IM: 3–10 units',
    pediatricDose: 'N/A'
  }
];

// Category color map (matches CSS)
const CATEGORY_COLORS = {
  'Cardiac': '#ef4444',
  'RSI': '#8b5cf6',
  'Pain': '#f59e0b',
  'Respiratory': '#06b6d4',
  'Overdose/Poisoning': '#84cc16',
  'Seizures': '#ec4899',
  'Diabetes': '#14b8a6',
  'Allergies': '#f97316',
  'OB/GYN': '#d946ef',
  'Chemical Restraint': '#6366f1',
  'Nausea/Vomiting': '#22c55e'
};

const CATEGORIES = [...new Set(DRUGS.map(d => d.category))].sort();

// Drug families for comparative learning — groups similar drugs so you can spot what makes each one different
const DRUG_FAMILIES = [
  {
    name: 'RSI Paralytics',
    icon: '💪',
    description: 'Neuromuscular blockers for paralysis',
    drugIds: ['rocuronium', 'vecuronium', 'succinylcholine'],
    keyDifference: 'Succinylcholine is the ONLY depolarizing agent — fastest onset, but malignant hyperthermia risk. Roc and Vec are non-depolarizing. Vecuronium is contraindicated in myasthenia gravis.'
  },
  {
    name: 'RSI Sedatives',
    icon: '😴',
    description: 'Pre-RSI sedation agents',
    drugIds: ['fentanyl-rsi', 'etomidate', 'droperidol', 'midazolam-rsi'],
    keyDifference: 'Etomidate = cleanest hemodynamics, common RSI dose 20 mg. Droperidol blocks dopamine (watch for dystonic reactions). Midazolam = benzo. Fentanyl = opioid analgesic. All cause respiratory depression.'
  },
  {
    name: 'Benzodiazepines',
    icon: '🧘',
    description: 'Diazepam & Midazolam — multiple uses',
    drugIds: ['diazepam-seizures', 'diazepam-cardiac', 'midazolam-seizures', 'midazolam-cardiac', 'midazolam-rsi'],
    keyDifference: 'Both treat seizures, premedicate cardioversion, and sedate RSI. Always watch RR — benzos drop respirations. Reverse with flumazenil (rarely carried).'
  },
  {
    name: 'Narcotic Analgesics',
    icon: '💊',
    description: 'Opioid pain control',
    drugIds: ['fentanyl-pain', 'morphine'],
    keyDifference: 'Fentanyl 25–100 mcg — fast, short, less hypotension. Morphine 2–10 mg SIVP — vasodilates (good for CHF/AMI), but more histamine release. Both ↓ RR — reverse with Narcan.'
  },
  {
    name: 'Vasopressors / Sympathomimetics',
    icon: '⬆️',
    description: 'Raise BP, cardiac stimulants',
    drugIds: ['epi-cardiac', 'dopamine', 'vasopressin'],
    keyDifference: 'Epi: arrest 1 mg 1:10,000. Dopamine: dose-dependent — 2–10 mcg/kg/min = inotrope, 10–20 = pressor. Vasopressin: 40 units ONE-TIME, replaces 1st or 2nd epi dose. Not for peds.'
  },
  {
    name: 'Cardiac Antidysrhythmics',
    icon: '💓',
    description: 'Control abnormal rhythms',
    drugIds: ['adenosine', 'amiodarone', 'lidocaine', 'procainamide', 'diltiazem', 'mag-cardiac', 'atropine-cardiac'],
    keyDifference: 'Adenosine = SVT only (6→12→12). Amiodarone = all tachys (300 then 150 in arrest). Lidocaine = V-fib/V-tach. Procainamide = all tachys. Diltiazem = A-fib/A-flutter/SVT. Mag = Torsades. Atropine = symptomatic brady.'
  },
  {
    name: 'Bronchodilators',
    icon: '🫁',
    description: 'Open airways in asthma/COPD',
    drugIds: ['albuterol', 'racemic-epi', 'ipratropium', 'epi-respiratory'],
    keyDifference: 'Albuterol = sympathomimetic, first-line. Ipratropium = anticholinergic, often combined (NOT after atropine). Racemic Epi = croup ONLY (NOT epiglottitis). Epi IM = severe asthma/COPD.'
  },
  {
    name: 'Nitrates / Vasodilators',
    icon: '🩸',
    description: 'Vasodilation, ↓ preload',
    drugIds: ['nitroglycerine', 'amyl-nitrate-cardiac'],
    keyDifference: 'NTG: SL 0.3–0.4 mg × 3 for cardiac chest pain. Amyl nitrate: vasodilator AND a cyanide antidote (turns Hgb into methemoglobin). Both: hypotension and recent ED drugs are contraindications.'
  },
  {
    name: 'Antidotes',
    icon: '🛡️',
    description: 'Specific poisoning reversals',
    drugIds: ['naloxone', 'atropine-od', 'pralidoxime', 'sodium-bicarb', 'calcium-chloride', 'glucagon-od', 'amyl-nitrate-od', 'diphenhydramine-od'],
    keyDifference: 'Narcan = opioids. Atropine + 2-PAM = organophosphates/nerve agents (atropine FIRST). Bicarb = TCA OD + hyperK. CaCl = CCB OD, hyperK, hyperMg. Glucagon = beta-blocker / CCB OD. Amyl nitrate = cyanide. Benadryl = dystonic reactions.'
  },
  {
    name: 'OB/GYN',
    icon: '🤰',
    description: 'Obstetric emergencies',
    drugIds: ['terbutaline', 'oxytocin', 'mag-ob'],
    keyDifference: 'Terbutaline = stops preterm labor (tocolytic, secondary to mag). Mag Sulfate = first-line eclampsia seizures + preterm labor. Oxytocin (Pitocin) = post-partum hemorrhage AFTER placenta delivers.'
  },
  {
    name: 'Diabetes / Glucose',
    icon: '🍬',
    description: 'Blood sugar management',
    drugIds: ['dextrose', 'glucagon-diabetes', 'thiamine'],
    keyDifference: 'D50 = first line if IV. Glucagon = no IV access (IM works, breaks down glycogen). Thiamine BEFORE D50 in alcoholics/DT — prevents Wernicke\'s encephalopathy.'
  }
];

// Field labels & questions used by Drill Mode
const FIELD_LABELS = {
  indications: 'Indications',
  class: 'Drug Class',
  action: 'Mechanism of Action',
  contraindications: 'Contraindications',
  sideEffects: 'Side Effects',
  adultDose: 'Adult Dose',
  pediatricDose: 'Pediatric Dose'
};

const FIELD_QUESTIONS = {
  indications: 'What are the indications?',
  class: 'What drug class is this?',
  action: 'What is the mechanism of action?',
  contraindications: 'What are the contraindications?',
  sideEffects: 'What are the side effects?',
  adultDose: 'What is the adult dose?',
  pediatricDose: 'What is the pediatric dose?'
};
